# -*- coding: utf-8 -*-
"""COCO 80 类：中文名、口语别名、用于测距的真实高度（米）。"""

# ---------------- 英文名 -> 中文名 ----------------
CLASS_CN = {
    "person": "人", "bicycle": "自行车", "car": "汽车", "motorcycle": "摩托车",
    "airplane": "飞机", "bus": "公交车", "train": "火车", "truck": "卡车",
    "boat": "船", "traffic light": "红绿灯", "fire hydrant": "消防栓",
    "stop sign": "停车标志", "parking meter": "停车计时器", "bench": "长凳",
    "bird": "鸟", "cat": "猫", "dog": "狗", "horse": "马", "sheep": "羊",
    "cow": "牛", "elephant": "大象", "bear": "熊", "zebra": "斑马",
    "giraffe": "长颈鹿", "backpack": "背包", "umbrella": "雨伞",
    "handbag": "手提包", "tie": "领带", "suitcase": "行李箱", "frisbee": "飞盘",
    "skis": "滑雪板", "snowboard": "滑雪板", "sports ball": "球", "kite": "风筝",
    "baseball bat": "棒球棒", "baseball glove": "棒球手套",
    "skateboard": "滑板", "surfboard": "冲浪板", "tennis racket": "网球拍",
    "bottle": "瓶子", "wine glass": "酒杯", "cup": "杯子", "fork": "叉子",
    "knife": "刀", "spoon": "勺子", "bowl": "碗", "banana": "香蕉",
    "apple": "苹果", "sandwich": "三明治", "orange": "橙子",
    "broccoli": "西兰花", "carrot": "胡萝卜", "hot dog": "热狗",
    "pizza": "披萨", "donut": "甜甜圈", "cake": "蛋糕", "chair": "椅子",
    "couch": "沙发", "potted plant": "盆栽", "bed": "床",
    "dining table": "餐桌", "toilet": "马桶", "tv": "电视",
    "laptop": "笔记本电脑", "mouse": "鼠标", "remote": "遥控器",
    "keyboard": "键盘", "cell phone": "手机", "microwave": "微波炉",
    "oven": "烤箱", "toaster": "烤面包机", "sink": "水槽",
    "refrigerator": "冰箱", "book": "书", "clock": "时钟", "vase": "花瓶",
    "scissors": "剪刀", "teddy bear": "玩具熊", "hair drier": "吹风机",
    "toothbrush": "牙刷",
    # ---- YOLO-World 家居扩展词表（英文提示词与 make_world_onnx.py 的 EXT 一致）----
    "earphones": "耳机", "medicine box": "药盒", "keys": "钥匙",
    "glasses": "眼镜", "charger": "充电器", "power bank": "充电宝",
    "charging cable": "数据线", "thermos cup": "保温杯", "slippers": "拖鞋",
    "tissue box": "纸巾盒", "comb": "梳子", "wallet": "钱包",
    "wristwatch": "手表", "pen": "笔", "notebook": "记事本",
    "kettle": "水壶", "rice cooker": "电饭煲", "electric fan": "电风扇",
    "pill bottle": "药瓶", "towel": "毛巾", "soap": "肥皂",
    "shampoo bottle": "洗发水", "toothpaste": "牙膏", "lunch box": "饭盒",
    "milk carton": "牛奶", "eggs": "鸡蛋", "desk lamp": "台灯",
    "alarm clock": "闹钟", "power strip": "插线板", "walking cane": "拐杖",
    "wheelchair": "轮椅", "walker": "助行器", "radio": "收音机",
    "calculator": "计算器", "hat": "帽子", "scarf": "围巾",
    "gloves": "手套", "trash bin": "垃圾桶", "flashlight": "手电筒",
    "battery": "电池",
}

# ---------------- 中文口语别名 -> 英文名 ----------------
ALIASES = {
    "人": "person", "行人": "person", "大人": "person", "小孩": "person",
    "自行车": "bicycle", "单车": "bicycle",
    "汽车": "car", "小汽车": "car", "轿车": "car", "车子": "car",
    "摩托车": "motorcycle", "电动车": "motorcycle",
    "飞机": "airplane", "公交车": "bus", "巴士": "bus", "公共汽车": "bus",
    "火车": "train", "卡车": "truck", "货车": "truck", "船": "boat",
    "红绿灯": "traffic light", "交通灯": "traffic light",
    "消防栓": "fire hydrant", "停车标志": "stop sign", "长凳": "bench",
    "长椅": "bench", "鸟": "bird", "小鸟": "bird", "猫": "cat", "猫咪": "cat",
    "狗": "dog", "小狗": "dog", "马": "horse", "羊": "sheep",
    "牛": "cow", "大象": "elephant", "熊": "bear", "斑马": "zebra",
    "长颈鹿": "giraffe", "背包": "backpack", "书包": "backpack",
    "雨伞": "umbrella", "伞": "umbrella", "手提包": "handbag",
    "包": "handbag", "领带": "tie", "行李箱": "suitcase", "箱子": "suitcase",
    "飞盘": "frisbee", "球": "sports ball", "风筝": "kite",
    "滑板": "skateboard", "网球拍": "tennis racket",
    "瓶子": "bottle", "水瓶": "bottle", "水杯": "cup", "杯子": "cup",
    "酒杯": "wine glass", "叉子": "fork", "刀": "knife", "勺子": "spoon",
    "碗": "bowl", "香蕉": "banana", "苹果": "apple",
    "三明治": "sandwich", "橙子": "orange", "橘子": "orange",
    "西兰花": "broccoli", "胡萝卜": "carrot", "热狗": "hot dog",
    "披萨": "pizza", "甜甜圈": "donut", "蛋糕": "cake",
    "椅子": "chair", "沙发": "couch", "盆栽": "potted plant",
    "床": "bed", "餐桌": "dining table", "桌子": "dining table",
    "马桶": "toilet", "电视": "tv", "电视机": "tv",
    "笔记本电脑": "laptop", "笔记本": "laptop", "电脑": "laptop",
    "鼠标": "mouse", "遥控器": "remote", "键盘": "keyboard",
    "手机": "cell phone", "电话": "cell phone",
    "微波炉": "microwave", "烤箱": "oven", "水槽": "sink",
    "冰箱": "refrigerator", "书": "book", "书本": "book",
    "时钟": "clock", "钟": "clock", "花瓶": "vase", "剪刀": "scissors",
    "玩具熊": "teddy bear", "小熊": "teddy bear", "泰迪熊": "teddy bear",
    "吹风机": "hair drier", "牙刷": "toothbrush",
    # ---- 家居扩展（语音说这些词，本地 YOLO-World 直接接单，不用 AI 兜底）----
    "耳机": "earphones", "蓝牙耳机": "earphones", "耳麦": "earphones",
    "药盒": "medicine box", "药箱": "medicine box",
    "钥匙": "keys", "钥匙串": "keys",
    "眼镜": "glasses", "老花镜": "glasses", "太阳镜": "glasses",
    "充电器": "charger", "充电头": "charger",
    "充电宝": "power bank", "移动电源": "power bank",
    "数据线": "charging cable", "充电线": "charging cable",
    "保温杯": "thermos cup", "保温壶": "thermos cup",
    "拖鞋": "slippers",
    "纸巾盒": "tissue box", "抽纸": "tissue box",
    "梳子": "comb",
    "钱包": "wallet",
    "手表": "wristwatch", "腕表": "wristwatch",
    "笔": "pen", "钢笔": "pen", "圆珠笔": "pen",
    "记事本": "notebook", "本子": "notebook",
    "水壶": "kettle", "烧水壶": "kettle", "电水壶": "kettle",
    "电饭煲": "rice cooker", "电饭锅": "rice cooker",
    "电风扇": "electric fan", "风扇": "electric fan",
    "药瓶": "pill bottle", "药罐": "pill bottle",
    "毛巾": "towel", "浴巾": "towel",
    "肥皂": "soap", "香皂": "soap",
    "洗发水": "shampoo bottle", "洗发露": "shampoo bottle",
    "牙膏": "toothpaste",
    "饭盒": "lunch box", "便当盒": "lunch box",
    "牛奶": "milk carton", "牛奶盒": "milk carton",
    "鸡蛋": "eggs",
    "台灯": "desk lamp", "桌灯": "desk lamp",
    "闹钟": "alarm clock",
    "插线板": "power strip", "排插": "power strip",
    "拐杖": "walking cane", "拐棍": "walking cane", "手杖": "walking cane",
    "轮椅": "wheelchair",
    "助行器": "walker",
    "收音机": "radio",
    "计算器": "calculator",
    "帽子": "hat",
    "围巾": "scarf",
    "手套": "gloves",
    "垃圾桶": "trash bin", "纸篓": "trash bin",
    "手电筒": "flashlight",
    "电池": "battery",
}

# ---------------- 各类真实世界高度（米），用于单目测距 ----------------
REAL_HEIGHT = {
    "person": 1.7, "bicycle": 1.1, "car": 1.5, "motorcycle": 1.2,
    "bus": 3.0, "truck": 3.0, "bottle": 0.25, "cup": 0.10,
    "cell phone": 0.15, "remote": 0.18, "book": 0.20, "laptop": 0.25,
    "chair": 0.9, "backpack": 0.5, "tv": 0.7, "keyboard": 0.15,
    "mouse": 0.04, "umbrella": 0.9, "cat": 0.25, "dog": 0.45,
    "earphones": 0.06, "medicine box": 0.08, "keys": 0.03,
    "glasses": 0.04, "charger": 0.05, "power bank": 0.1,
    "charging cable": 0.05, "thermos cup": 0.18, "slippers": 0.08,
    "tissue box": 0.12, "comb": 0.03, "wallet": 0.03, "wristwatch": 0.03,
    "pen": 0.02, "notebook": 0.02, "kettle": 0.2, "rice cooker": 0.25,
    "electric fan": 0.4, "pill bottle": 0.08, "towel": 0.05,
    "soap": 0.03, "shampoo bottle": 0.2, "toothpaste": 0.04,
    "lunch box": 0.08, "milk carton": 0.18, "eggs": 0.05,
    "desk lamp": 0.35, "alarm clock": 0.1, "power strip": 0.05,
    "walking cane": 0.85, "wheelchair": 0.9, "walker": 0.8,
    "radio": 0.15, "calculator": 0.03, "hat": 0.15, "scarf": 0.1,
    "gloves": 0.03, "trash bin": 0.4, "flashlight": 0.15,
    "battery": 0.03,
}


def match_target(text):
    """从一句话里按最长别名匹配目标，返回英文名；匹配不到返回 None。"""
    for alias in sorted(ALIASES, key=len, reverse=True):
        if alias in text:
            return ALIASES[alias]
    return None
